[package]
license-files.exclude = [
  "opus/COPYING",
  "opus/LICENSE_PLEASE_READ.txt"
]

[features]
# shouldn't be needed, uses outdated bindgen
hide = [
  "bindgen",
  "generate_binding",
]

[scripts]
# drop vendored version of opus, it's part of Fedora
prep.post = ["rm -rf opus"]

[requires]
build = ["pkgconfig(opus) >= 1.0.0"]
lib = ["pkgconfig(opus) >= 1.0.0"]

