[package]
extra-patches = [
  { number = 10, file = "sspi-fix-metadata.diff", comments = ["default to the ring crypto backend"] },
]

[features]
# missing deps or internal
hide = [
    "aws-lc-rs",
    "scard", 
    "__test-data", 
    "__rustls-used", 
    "__install-crypto-provider",
]
