[package]
cargo-toml-patch-comments = [
    "default to the ring crypto backend",
]

[features]
# missing deps or internal
hide = [
    "aws-lc-rs",
    "scard", 
    "__test-data", 
    "__rustls-used", 
    "__install-crypto-provider",
]
